services:
  identityserverhost:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/identity.pfx
    ports:
      - "8080"
      - "5001:8081"

  helloworldapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/helloworld.pfx
      - IdentityServer__BaseUrl=https://identityserverhost:8081
      - Redis__Host=redis
    ports:
      - "8080"
      - "5002:8081"

  consumerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - IdentityServer__BaseUrl=https://identityserverhost:8081
      - HelloWorldApi__BaseUrl=https://helloworldapi:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/consumer.pfx
    ports:
      - "5003:8081"
